"""RoBench-25 — the long-context retrieval benchmark released with HiSPA
(Le Mercier, Develder & Demeester, arXiv:2601.01972).

Correct description (the audit found the previous one inflated):
**120 abstracts of accepted NeurIPS-2025 papers with 240 true/false
questions (2 per abstract)**, evaluated with and without trigger insertion
between the abstract and the question.  There is no separate "1,050 triggers
/ nine families" release; triggers are generated by Z-HiSPA / M-HiSPA at
evaluation time.  The authors' release is an anonymised 4open.science
repository; ``path`` should point to its JSONL export with fields

    {"abstract_id": int, "abstract": str, "question": str, "answer": bool}

An optional ``trigger`` field may be present for pre-generated triggers.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

N_ABSTRACTS = 120
N_QUESTIONS = 240


@dataclass
class RoBenchItem:
    abstract_id: int
    abstract: str
    question: str
    answer: bool
    trigger: str | None = None

    def prompt(self, trigger: str | None = None, template: str = "{abstract}\n{trigger}\nQuestion: {question}\nAnswer (true/false):") -> str:
        t = trigger if trigger is not None else (self.trigger or "")
        return template.format(abstract=self.abstract, trigger=t, question=self.question)


class RoBenchDataset:
    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)
        if not self.path.exists():
            raise FileNotFoundError(
                f"RoBench-25 file {self.path} not found. Obtain the authors' anonymised release "
                "(see docs/DATASETS.md) and export it to JSONL."
            )

    def __iter__(self) -> Iterator[RoBenchItem]:
        with open(self.path, encoding="utf-8") as fh:
            for line in fh:
                if not line.strip():
                    continue
                o = json.loads(line)
                yield RoBenchItem(abstract_id=int(o["abstract_id"]), abstract=o["abstract"],
                                  question=o["question"], answer=bool(o["answer"]), trigger=o.get("trigger"))

    def to_list(self) -> list[RoBenchItem]:
        return list(self)

    def validate(self) -> dict:
        items = self.to_list()
        n_abs = len({i.abstract_id for i in items})
        return {"n_questions": len(items), "n_abstracts": n_abs,
                "matches_release": (len(items) == N_QUESTIONS and n_abs == N_ABSTRACTS)}
